# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vtuber.grpc.v1 import core_pb2 as vtuber_dot_v1_dot_core__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vtuber/v1/core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VtuberCoreStub(object):
    """Gateway ↔ Core 双向会话（持续 PCM 进、媒体+事件出）
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectSession = channel.stream_stream(
                '/vtuber.v1.VtuberCore/ConnectSession',
                request_serializer=vtuber_dot_v1_dot_core__pb2.GatewayToCore.SerializeToString,
                response_deserializer=vtuber_dot_v1_dot_core__pb2.CoreToGateway.FromString,
                _registered_method=True)


class VtuberCoreServicer(object):
    """Gateway ↔ Core 双向会话（持续 PCM 进、媒体+事件出）
    """

    def ConnectSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VtuberCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectSession': grpc.stream_stream_rpc_method_handler(
                    servicer.ConnectSession,
                    request_deserializer=vtuber_dot_v1_dot_core__pb2.GatewayToCore.FromString,
                    response_serializer=vtuber_dot_v1_dot_core__pb2.CoreToGateway.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vtuber.v1.VtuberCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vtuber.v1.VtuberCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VtuberCore(object):
    """Gateway ↔ Core 双向会话（持续 PCM 进、媒体+事件出）
    """

    @staticmethod
    def ConnectSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/vtuber.v1.VtuberCore/ConnectSession',
            vtuber_dot_v1_dot_core__pb2.GatewayToCore.SerializeToString,
            vtuber_dot_v1_dot_core__pb2.CoreToGateway.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
